// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA733Ot4yK95HLjauIeE2Qi-9m3zxIsmio',
    appId: '1:55240641303:web:566ab6a1404f67d38e4552',
    messagingSenderId: '55240641303',
    projectId: 'marketing-jagaddhitamp',
    authDomain: 'marketing-jagaddhitamp.firebaseapp.com',
    storageBucket: 'marketing-jagaddhitamp.firebasestorage.app',
    measurementId: 'G-G1R1L5PZ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3BImWXut4Kp4pxRjXuk8K8WF0KUQP_o',
    appId: '1:55240641303:android:4e91fd15bff6ac6a8e4552',
    messagingSenderId: '55240641303',
    projectId: 'marketing-jagaddhitamp',
    storageBucket: 'marketing-jagaddhitamp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjr0iKIVwGRkDO2G0NS25-pF2MxBxex8',
    appId: '1:55240641303:ios:08eee12ba125449a8e4552',
    messagingSenderId: '55240641303',
    projectId: 'marketing-jagaddhitamp',
    storageBucket: 'marketing-jagaddhitamp.firebasestorage.app',
    iosClientId: '55240641303-4mamlhen08r26f705l4abvt6gl4bka52.apps.googleusercontent.com',
    iosBundleId: 'com.jagaddhitagroup.marketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBppwhf7FtkD7R6d61cRYN5s3NOtrPGw1E',
    appId: '1:556031650608:web:9575c9ac562c5e036cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-jagaddhitamp',
    authDomain: 'marketing-jagaddhitamp.firebaseapp.com',
    databaseURL: 'https://marketing-jagaddhitamp-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-jagaddhitamp.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJD_YwC3DMoB9m9DNWX3zZkJjcz8AlDr8',
    appId: '1:556031650608:ios:7cc3bdea1103a76f6cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-jagaddhitamp',
    databaseURL: 'https://marketing-jagaddhitamp-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-jagaddhitamp.firebasestorage.app',
    iosClientId: '556031650608-8ckg1654u797nlrdjm0kfg1kcqkdc3au.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketingPenerbitJagaddhita',
  );

}